### ISSUE TITLE
Strong magnets vs. the battery holder

### ISSUE THREAD

**Issue by vielmetti** [lab11/blees#5]
I have a set of strong magnets that were originally sourced for an "LED throwie" project. The idea is that you wire up a little circuit, attach a magnet, and then throw the device to hope to stick on a wall or sign or whatever. 

The magnets that I have stick nicely to the BLEES, but the design of the battery holder is such that the device will lose power when stuck to this magnet because the holder has just enough wiggle room that when the battery is stuck to the magnet it gets disconnected from the device.

If I read it right, the Squall is the actual place where the issue is, and I was looking for the bill of materials for that device and didn't see it in this repo.

**Comment by prabaldutta** [comment]
See:
http://lab11.eecs.umich.edu/content/pcb/squall/a/squall.pdf
and
http://lab11.eecs.umich.edu/content/pcb/squall/a/squall_a_2014-10-08.zip
linked from:
http://lab11.eecs.umich.edu/pcb.html
- Prabal

**Comment by uint-nate** [comment]
In addition to the links above, here's the link to the Squall Github repo: 
https://github.com/helena-project/squall

**Comment by bradjc** [comment]
Our solution right now is to put more solder on the GND pad under the batter holder. Seems to work.
